use super::{
    client::DatabaseClient,
    structure,
    table_changes::TransactionGuard,
    table_data::{qualified_name as qualified_table, quote_identifier},
};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{
    collections::HashSet,
    sync::atomic::{AtomicBool, Ordering},
    time::Duration,
};

mod constraints;
pub(crate) mod enums;
use constraints::ConstraintChange;

#[derive(Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub(crate) enum DefaultMode {
    #[default]
    Keep,
    Literal,
    Drop,
    CurrentTimestamp,
    RandomUuid,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct ColumnDraft {
    pub original: Option<String>,
    pub name: String,
    pub data_type: String,
    #[serde(default)]
    pub enum_type: Option<enums::EnumRef>,
    pub nullable: bool,
    pub primary_key: bool,
    pub default_value: Option<String>,
    #[serde(default)]
    pub default_mode: DefaultMode,
    pub identity: bool,
    pub removed: bool,
}
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct SchemaChange {
    pub schema: String,
    pub table: String,
    pub original: Option<String>,
    pub expected: Option<Value>,
    pub columns: Vec<ColumnDraft>,
    pub drop_table: bool,
    #[serde(default)]
    pub constraints: Vec<ConstraintChange>,
    #[serde(default)]
    pub enum_changes: Vec<enums::EnumDraft>,
}
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct Plan {
    pub sql: String,
    pub destructive: bool,
}
#[derive(Serialize)]
pub(crate) struct ChangeError {
    pub kind: &'static str,
    pub message: String,
}
impl ChangeError {
    pub fn rejected(message: impl Into<String>) -> Self {
        Self {
            kind: "rejected",
            message: message.into(),
        }
    }
    pub fn unknown() -> Self {
        Self { kind: "unknown", message: "Commit outcome is unknown. Reconnect and inspect the table before making another change. This request will not be retried.".into() }
    }
}

fn name(value: &str) -> Result<(), String> {
    if value.trim().is_empty() || value.len() > 63 || value.contains('\0') {
        return Err("Names must contain 1–63 UTF-8 bytes and no null character.".into());
    }
    Ok(())
}
fn column_type(value: &str) -> Result<(), String> {
    // ponytail: a bounded built-in type picker; advanced types/expressions remain in SQL until a typed editor supports them.
    if ![
        "text",
        "boolean",
        "smallint",
        "integer",
        "bigint",
        "numeric",
        "real",
        "double precision",
        "uuid",
        "date",
        "timestamp",
        "timestamptz",
        "json",
        "jsonb",
        "bytea",
    ]
    .contains(&value)
    {
        return Err("Choose a supported built-in column type.".into());
    }
    Ok(())
}

fn default_sql(column: &ColumnDraft) -> Result<Option<String>, String> {
    match column.default_mode {
        DefaultMode::Drop => return Ok(None),
        DefaultMode::CurrentTimestamp => return Ok(Some("CURRENT_TIMESTAMP".into())),
        DefaultMode::RandomUuid => return Ok(Some("pg_catalog.gen_random_uuid()".into())),
        DefaultMode::Literal if column.default_value.is_none() => {
            return Err(
                "A literal default requires a value; choose No default to remove it.".into(),
            );
        }
        _ => {}
    }
    column
        .default_value
        .as_ref()
        .map(|value| {
            if value.len() > 4096 || value.contains('\0') {
                return Err(
                    "Default value exceeds 4096 bytes or contains a null character.".into(),
                );
            }
            Ok(format!(
                "E'{}'",
                value.replace('\\', "\\\\").replace('\'', "''")
            ))
        })
        .transpose()
}

fn definition(column: &ColumnDraft) -> Result<String, String> {
    name(&column.name)?;
    let data_type = type_sql(column)?;
    if column.identity
        && (!matches!(column.data_type.as_str(), "smallint" | "integer" | "bigint")
            || default_sql(column)?.is_some())
    {
        return Err("Identity requires an integer type and no default value.".into());
    }
    let mut sql = format!("{} {}", quote_identifier(&column.name), data_type);
    if column.identity {
        sql.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if let Some(value) = default_sql(column)? {
        sql.push_str(&format!(" DEFAULT {value}"));
    }
    if !column.nullable || column.primary_key || column.identity {
        sql.push_str(" NOT NULL");
    }
    Ok(sql)
}

fn type_sql(column: &ColumnDraft) -> Result<String, String> {
    if let Some(reference) = &column.enum_type {
        let sql = enums::reference(reference)?;
        if column.data_type != sql || column.identity {
            return Err("Invalid enum column type or identity.".into());
        }
        Ok(sql)
    } else {
        column_type(&column.data_type)?;
        Ok(column.data_type.clone())
    }
}

fn alter_column(column: &ColumnDraft, old: &Value, target: &str) -> Result<Vec<String>, String> {
    let changed_type = old["dataType"] != column.data_type;
    let changed_nullable = old["nullable"] != column.nullable;
    if old["primaryKey"] != column.primary_key || old["identity"] != column.identity {
        return Err("Changing an existing primary key or identity requires SQL.".into());
    }
    if old["generated"] == true
        && (changed_type || changed_nullable || column.default_mode != DefaultMode::Keep)
    {
        return Err("Generated column properties require SQL.".into());
    }
    if column.nullable && (column.primary_key || column.identity) {
        return Err("Primary key and identity columns cannot allow NULL.".into());
    }
    if column.identity && column.default_mode != DefaultMode::Keep {
        return Err("Identity columns cannot have an ordinary default.".into());
    }
    let mut sql = Vec::new();
    let prefix = format!(
        "ALTER TABLE ONLY {target} ALTER COLUMN {}",
        quote_identifier(&column.name)
    );
    // Drop an explicitly replaced default before the type change; unchanged expressions never get reinterpreted as literals.
    if column.default_mode != DefaultMode::Keep {
        sql.push(format!("{prefix} DROP DEFAULT;"));
    } else if old["defaultValue"] != serde_json::to_value(&column.default_value).unwrap() {
        return Err("Choose an explicit default action before replacing a default.".into());
    }
    if changed_type {
        let data_type = type_sql(column)?;
        // No guessed USING expression: PostgreSQL must support the assignment cast or reject the entire transaction.
        sql.push(format!("{prefix} TYPE {data_type};"));
    }
    if changed_nullable {
        sql.push(format!(
            "{prefix} {} NOT NULL;",
            if column.nullable { "DROP" } else { "SET" }
        ));
    }
    if column.default_mode != DefaultMode::Keep {
        if let Some(value) = default_sql(column)? {
            sql.push(format!("{prefix} SET DEFAULT {value};"));
        }
    }
    Ok(sql)
}

pub(crate) fn plan(input: &SchemaChange) -> Result<Plan, String> {
    name(&input.schema)?;
    name(&input.table)?;
    if input.schema == "information_schema" || input.schema.starts_with("pg_") {
        return Err("System schemas cannot be edited here.".into());
    }
    if input.columns.len() > 500 {
        return Err(
            "The structure editor supports up to 500 columns. Use SQL for larger tables.".into(),
        );
    }
    let target = qualified_table(
        &input.schema,
        input.original.as_deref().unwrap_or(&input.table),
    );
    if input.drop_table && !input.enum_changes.is_empty() {
        return Err("Apply enum changes separately from dropping a table.".into());
    }
    let mut statements = enums::plan(&input.enum_changes)?;
    let mut destructive = input.drop_table;
    let (before, after, risky) = constraints::plan(input, &target)?;
    destructive |= risky;
    statements.extend(before);
    if let Some(original) = &input.original {
        name(original)?;
        let expected = input
            .expected
            .as_ref()
            .ok_or("Load the structure before editing.")?;
        if expected["objectType"] != "Table" || !expected["relationOid"].is_u64() {
            return Err("Only ordinary, non-inherited tables can be edited here. Use SQL for other objects.".into());
        }
        if input.drop_table {
            statements.push(format!("DROP TABLE {target} RESTRICT;"));
        } else {
            let old = expected["columns"]
                .as_array()
                .ok_or("Missing column snapshot.")?;
            let originals: HashSet<_> = input
                .columns
                .iter()
                .filter_map(|c| c.original.as_deref())
                .collect();
            if originals.len() != old.len()
                || old
                    .iter()
                    .any(|c| !originals.contains(c["name"].as_str().unwrap_or("")))
                || input
                    .columns
                    .iter()
                    .filter(|c| c.original.is_some())
                    .count()
                    != old.len()
            {
                return Err("The column snapshot is incomplete. Reload the editor.".into());
            }
            let mut names = HashSet::new();
            for column in input.columns.iter().filter(|c| !c.removed) {
                name(&column.name)?;
                if !names.insert(&column.name) {
                    return Err("Column names must be unique.".into());
                }
            }
            for column in &input.columns {
                if let Some(from) = &column.original {
                    name(from)?;
                    let prior = old
                        .iter()
                        .find(|c| c["name"] == *from)
                        .ok_or("Missing original column.")?;
                    if column.removed {
                        destructive = true;
                        statements.push(format!(
                            "ALTER TABLE ONLY {target} DROP COLUMN {} RESTRICT;",
                            quote_identifier(from)
                        ));
                    } else if from != &column.name {
                        // Reject swaps/cycles instead of inventing temporary names.
                        if originals.contains(column.name.as_str()) {
                            return Err("Rename to an unused column name, then apply before reusing an old name.".into());
                        }
                        statements.push(format!(
                            "ALTER TABLE ONLY {target} RENAME COLUMN {} TO {};",
                            quote_identifier(from),
                            quote_identifier(&column.name)
                        ));
                    }
                    if !column.removed {
                        destructive |= prior["dataType"] != column.data_type;
                        statements.extend(alter_column(column, prior, &target)?);
                    }
                } else if !column.removed {
                    if column.primary_key {
                        return Err(
                            "Adding a primary key to an existing table requires SQL.".into()
                        );
                    }
                    statements.push(format!(
                        "ALTER TABLE ONLY {target} ADD COLUMN {};",
                        definition(column)?
                    ));
                }
            }
        }
    } else {
        if input.drop_table
            || input.expected.is_some()
            || input.columns.iter().any(|c| c.original.is_some())
        {
            return Err("Invalid new table draft.".into());
        }
        let mut names = HashSet::new();
        let mut columns = Vec::new();
        let mut keys = Vec::new();
        for column in input.columns.iter().filter(|c| !c.removed) {
            if !names.insert(&column.name) {
                return Err("Column names must be unique.".into());
            }
            columns.push(definition(column)?);
            if column.primary_key {
                keys.push(quote_identifier(&column.name));
            }
        }
        if columns.is_empty() {
            return Err("Add at least one column.".into());
        }
        if !keys.is_empty() {
            columns.push(format!("PRIMARY KEY ({})", keys.join(", ")));
        }
        statements.push(format!(
            "CREATE TABLE {target} (\n  {}\n);",
            columns.join(",\n  ")
        ));
    }
    statements.extend(after);
    if input
        .original
        .as_ref()
        .is_some_and(|original| original != &input.table)
        && !input.drop_table
    {
        statements.push(format!(
            "ALTER TABLE {target} RENAME TO {};",
            quote_identifier(&input.table)
        ));
    }
    if statements.is_empty() {
        return Err("There are no structure changes to apply.".into());
    }
    Ok(Plan {
        sql: statements.join("\n"),
        destructive,
    })
}

pub(crate) async fn apply(
    client: &DatabaseClient,
    input: &SchemaChange,
    confirmation: &str,
    committing: &AtomicBool,
    tls: Option<rustls::ClientConfig>,
) -> Result<(), ChangeError> {
    let plan = plan(input).map_err(ChangeError::rejected)?;
    if plan.destructive
        && confirmation
            != format!(
                "{}.{}",
                input.schema,
                input.original.as_deref().unwrap_or(&input.table)
            )
    {
        return Err(ChangeError::rejected(
            "Confirm the full table name before applying potentially destructive changes.",
        ));
    }
    let mut guard = TransactionGuard {
        client,
        tls,
        finished: false,
    };
    client
        .batch_execute(
            "BEGIN; SET LOCAL statement_timeout = '25000ms'; SET LOCAL lock_timeout = '5000ms';",
        )
        .await
        .map_err(|_| {
            ChangeError::rejected("Could not begin schema change. Reconnect and inspect the table.")
        })?;
    let result: Result<(), String> = async {
        if let Some(original) = &input.original {
            client.batch_execute(&format!("LOCK TABLE ONLY {} IN ACCESS EXCLUSIVE MODE", qualified_table(&input.schema, original))).await.map_err(|e| e.to_string())?;
            let snapshot = structure::inspect(client, &input.schema, original).await?;
            let inherited: bool = client.query_one("SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_inherits WHERE inhrelid = $1 OR inhparent = $1)", &[&snapshot.relation_oid]).await.map_err(|e| e.to_string())?.get(0);
            if inherited { return Err("Inherited and partitioned tables require SQL; no changes were applied.".into()); }
            if Some(serde_json::to_value(snapshot).map_err(|e| e.to_string())?) != input.expected { return Err("The table structure changed since this draft was opened. Discard and reopen the editor before applying.".into()); }
        }
        enums::verify(client, &input.enum_changes, false).await?;
        client.batch_execute("SET LOCAL search_path = pg_catalog").await.map_err(|e| e.to_string())?;
        client.batch_execute(&plan.sql).await.map_err(|e| e.as_db_error().map(|db| db.message().to_string()).unwrap_or_else(|| "Database connection failed.".into()))?;
        enums::verify(client, &input.enum_changes, true).await?;
        enums::verify_references(client, &input.columns).await.map_err(|e| e.message)?;
        Ok(())
    }.await;
    if let Err(message) = result {
        guard.finished = matches!(
            tokio::time::timeout(Duration::from_secs(3), client.batch_execute("ROLLBACK")).await,
            Ok(Ok(()))
        );
        return Err(ChangeError::rejected(format!(
            "Nothing was applied. {message}"
        )));
    }
    committing.store(true, Ordering::SeqCst);
    match client.batch_execute("COMMIT").await {
        Ok(()) => {
            guard.finished = true;
            Ok(())
        }
        Err(error)
            if error.as_db_error().is_some_and(|db| {
                !matches!(db.severity(), "FATAL" | "PANIC") && !db.code().code().starts_with("08")
            }) =>
        {
            guard.finished = matches!(
                tokio::time::timeout(Duration::from_secs(3), client.batch_execute("ROLLBACK"))
                    .await,
                Ok(Ok(()))
            );
            Err(ChangeError::rejected(
                "The database rejected the commit. Nothing was applied.",
            ))
        }
        Err(_) => Err(ChangeError::unknown()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn altering_columns_preserves_expressions_and_validates_every_change() {
        let old = serde_json::json!({"name":"value", "dataType":"integer", "nullable":true, "primaryKey":false, "identity":false, "generated":false, "defaultValue":"42"});
        let mut column: ColumnDraft = serde_json::from_value(serde_json::json!({"original":"value", "name":"value", "dataType":"bigint", "nullable":false,"primaryKey":false,"identity":false,"removed":false,"defaultValue":"42"})).unwrap();
        let sql = alter_column(&column, &old, "\"public\".\"items\"")
            .unwrap()
            .join("\n");
        assert!(sql.contains("TYPE bigint"));
        assert!(sql.contains("SET NOT NULL"));
        assert!(!sql.contains("DEFAULT"));
        column.default_mode = DefaultMode::Literal;
        column.default_value = None;
        assert!(default_sql(&column).is_err());
        column.default_value = Some("".into());
        let sql = alter_column(&column, &old, "t").unwrap().join("\n");
        assert!(sql.starts_with("ALTER TABLE ONLY t ALTER COLUMN \"value\" DROP DEFAULT;"));
        assert!(sql.ends_with("SET DEFAULT E'';"));
        column.data_type = "text; DROP TABLE items; --".into();
        assert!(alter_column(&column, &old, "t").is_err());
        column.data_type = "integer".into();
        column.identity = true;
        assert!(alter_column(&column, &old, "t").is_err());
        column.identity = false;
        let mut generated = old.clone();
        generated["generated"] = true.into();
        assert!(alter_column(&column, &generated, "t").is_err());
    }
    #[test]
    fn plans_quote_names_and_literals_and_reject_injection() {
        let mut input: SchemaChange = serde_json::from_value(serde_json::json!({"schema":"public","table":"a\"b","original":null,"expected":null,"dropTable":false,"columns":[{"original":null,"name":"x","dataType":"text","nullable":true,"primaryKey":false,"defaultValue":"'); DROP TABLE users; --", "identity":false,"removed":false}]})).unwrap();
        assert_eq!(plan(&input).unwrap().sql, "CREATE TABLE \"public\".\"a\"\"b\" (\n  \"x\" text DEFAULT E'''); DROP TABLE users; --'\n);");
        input.columns[0].data_type = "text); DROP TABLE users; --".into();
        assert!(plan(&input).is_err());
        input.columns[0].data_type = "text".into();
        input.table = "é".repeat(32);
        assert!(plan(&input).is_err());
    }

    async fn draft(client: &DatabaseClient, schema: &str, table: &str) -> SchemaChange {
        let snapshot = structure::inspect(client, schema, table).await.unwrap();
        let columns = snapshot
            .columns
            .iter()
            .map(|c| ColumnDraft {
                original: Some(c.column.name.clone()),
                name: c.column.name.clone(),
                data_type: c.column.data_type.clone(),
                enum_type: None,
                nullable: c.column.nullable,
                primary_key: c.column.primary_key,
                default_value: c.column.default_value.clone(),
                default_mode: DefaultMode::Keep,
                identity: c.column.identity,
                removed: false,
            })
            .collect();
        SchemaChange {
            schema: schema.into(),
            table: table.into(),
            original: Some(table.into()),
            expected: Some(serde_json::to_value(snapshot).unwrap()),
            columns,
            drop_table: false,
            constraints: vec![],
            enum_changes: vec![],
        }
    }

    #[tokio::test]
    #[ignore = "requires disposable PostgreSQL via OPALINE_TEST_POSTGRES_PORT"]
    async fn schema_crud_is_atomic_checks_snapshots_and_restricts_dependencies() {
        let port = std::env::var("OPALINE_TEST_POSTGRES_PORT")
            .expect("Set OPALINE_TEST_POSTGRES_PORT to a disposable PostgreSQL server");
        let (client, _) =
            crate::database::postgres::connect(&crate::database::models::ConnectionConfig {
                name: "Schema editor test".into(),
                host: "127.0.0.1".into(),
                port: port.parse().unwrap(),
                database: "postgres".into(),
                username: "postgres".into(),
                password: "opaline_test".into(),
                ssl_mode: crate::database::models::SslMode::Disable,
                ca_path: None,
                read_only: false,
            })
            .await
            .unwrap();
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let schema = format!("opaline_schema_{nonce}");
        client
            .batch_execute(&format!("CREATE SCHEMA {}", quote_identifier(&schema)))
            .await
            .unwrap();
        let mut input: SchemaChange = serde_json::from_value(serde_json::json!({"schema":schema,"table":"orders","original":null,"expected":null,"dropTable":false,"columns":[{"original":null,"name":"id","dataType":"bigint","nullable":false,"primaryKey":true,"defaultValue":null,"identity":true,"removed":false}]})).unwrap();
        let committing = AtomicBool::new(false);
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        let target = qualified_table(&schema, "orders");
        client
            .batch_execute(&format!("INSERT INTO {target} DEFAULT VALUES"))
            .await
            .unwrap();
        let metrics = qualified_table(&schema, "metrics");
        client.batch_execute(&format!("CREATE TABLE {metrics} (order_id bigint, score integer DEFAULT 7); INSERT INTO {metrics} VALUES (1,NULL)")).await.unwrap();
        let mut edit = draft(&client, &schema, "metrics").await;
        edit.columns[1].nullable = false;
        edit.columns[1].data_type = "bigint".into();
        edit.columns[1].default_mode = DefaultMode::Literal;
        edit.columns[1].default_value = Some("9".into());
        let confirmation = format!("{schema}.metrics");
        assert!(apply(&client, &edit, &confirmation, &committing, None)
            .await
            .is_err());
        assert_eq!(
            structure::inspect(&client, &schema, "metrics")
                .await
                .unwrap()
                .columns[1]
                .column
                .data_type,
            "integer"
        );
        client
            .batch_execute(&format!("UPDATE {metrics} SET score = 3"))
            .await
            .unwrap();
        edit.constraints = serde_json::from_value(serde_json::json!([
            {"kind":"createIndex","name":"metrics_score_idx","columns":["score"],"unique":false},
            {"kind":"addForeignKey","name":"metrics_order_fk","columns":["order_id"],"targetSchema":schema,"targetTable":"orders","targetColumns":["id"],"onDelete":"NO ACTION","onUpdate":"NO ACTION"}
        ])).unwrap();
        assert!(apply(&client, &edit, &confirmation, &committing, None)
            .await
            .is_ok());
        let inspected = structure::inspect(&client, &schema, "metrics")
            .await
            .unwrap();
        assert_eq!(inspected.columns[1].column.data_type, "bigint");
        assert!(!inspected.columns[1].column.nullable);
        assert!(inspected
            .indexes
            .iter()
            .any(|i| i.name == "metrics_score_idx"));
        assert!(inspected
            .foreign_keys
            .iter()
            .any(|i| i.name == "metrics_order_fk"));
        // A failing FK replacement rolls back its DROP and every other staged change.
        edit = draft(&client, &schema, "metrics").await;
        edit.constraints = serde_json::from_value(serde_json::json!([
            {"kind":"dropForeignKey","name":"metrics_order_fk"},
            {"kind":"dropIndex","name":"metrics_score_idx"},
            {"kind":"addForeignKey","name":"bad_fk","columns":["score"],"targetSchema":schema,"targetTable":"orders","targetColumns":["id"],"onDelete":"NO ACTION","onUpdate":"NO ACTION"}
        ])).unwrap();
        assert!(apply(&client, &edit, &confirmation, &committing, None)
            .await
            .is_err());
        let inspected = structure::inspect(&client, &schema, "metrics")
            .await
            .unwrap();
        assert!(inspected
            .foreign_keys
            .iter()
            .any(|i| i.name == "metrics_order_fk"));
        assert!(inspected
            .indexes
            .iter()
            .any(|i| i.name == "metrics_score_idx"));
        edit.constraints.pop();
        assert!(apply(&client, &edit, &confirmation, &committing, None)
            .await
            .is_ok());
        client
            .batch_execute(&format!("DROP TABLE {metrics} RESTRICT"))
            .await
            .unwrap();
        input = draft(&client, &schema, "orders").await;
        input.columns.push(ColumnDraft {
            original: None,
            name: "note".into(),
            data_type: "text".into(),
            enum_type: None,
            nullable: true,
            primary_key: false,
            default_value: Some("'); DROP TABLE orders; --".into()),
            default_mode: DefaultMode::Keep,
            identity: false,
            removed: false,
        });
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        assert_eq!(
            client
                .query_one(&format!("SELECT note FROM {target}"), &[])
                .await
                .unwrap()
                .get::<_, String>(0),
            "'); DROP TABLE orders; --"
        );
        // The old snapshot must not be accepted, even when the SQL itself could work.
        assert!(apply(&client, &input, "", &committing, None)
            .await
            .err()
            .unwrap()
            .message
            .contains("structure changed"));
        input = draft(&client, &schema, "orders").await;
        input.columns[0].name = "order_id".into();
        input.columns.push(ColumnDraft {
            original: None,
            name: "required".into(),
            data_type: "text".into(),
            enum_type: None,
            nullable: false,
            primary_key: false,
            default_value: None,
            default_mode: DefaultMode::Keep,
            identity: false,
            removed: false,
        });
        assert!(apply(&client, &input, "", &committing, None).await.is_err());
        // The successful rename preceding the NOT NULL failure was rolled back.
        assert_eq!(
            structure::inspect(&client, &schema, "orders")
                .await
                .unwrap()
                .columns[0]
                .column
                .name,
            "id"
        );
        input.columns.pop();
        input.table = "purchases".into();
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        let renamed = qualified_table(&schema, "purchases");
        client
            .batch_execute(&format!(
                "CREATE VIEW {} AS SELECT * FROM {renamed}",
                qualified_table(&schema, "dependent")
            ))
            .await
            .unwrap();
        input = draft(&client, &schema, "purchases").await;
        input.drop_table = true;
        assert!(apply(&client, &input, "wrong", &committing, None)
            .await
            .is_err());
        assert!(apply(
            &client,
            &input,
            &format!("{schema}.purchases"),
            &committing,
            None
        )
        .await
        .is_err());
        assert!(structure::inspect(&client, &schema, "purchases")
            .await
            .is_ok());
        client
            .batch_execute(&format!(
                "DROP VIEW {}",
                qualified_table(&schema, "dependent")
            ))
            .await
            .unwrap();
        input = draft(&client, &schema, "purchases").await;
        input.columns[1].removed = true;
        assert!(apply(
            &client,
            &input,
            &format!("{schema}.purchases"),
            &committing,
            None
        )
        .await
        .is_ok());
        assert_eq!(
            structure::inspect(&client, &schema, "purchases")
                .await
                .unwrap()
                .columns
                .len(),
            1
        );
        input = draft(&client, &schema, "purchases").await;
        input.drop_table = true;
        assert!(apply(
            &client,
            &input,
            &format!("{schema}.purchases"),
            &committing,
            None
        )
        .await
        .is_ok());
        assert!(structure::inspect(&client, &schema, "purchases")
            .await
            .is_err());
        // Enum creation and a table using it share the same reviewed transaction.
        let enum_name = qualified_table(&schema, "status");
        input = serde_json::from_value(serde_json::json!({
            "schema": schema, "table": "enum_items", "original": null,
            "expected": null, "dropTable": false,
            "columns": [{"original":null,"name":"status","dataType":enum_name,
                "enumType":{"schema":schema,"name":"status"},"nullable":true,
                "primaryKey":false,"identity":false,"removed":false,
                "defaultValue":"draft","defaultMode":"literal"}],
            "enumChanges":[{"schema":schema,"name":"status","original":null,"values":["draft","ready"]}]
        })).unwrap();
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        let enum_table = qualified_table(&schema, "enum_items");
        client
            .batch_execute(&format!("INSERT INTO {enum_table} DEFAULT VALUES"))
            .await
            .unwrap();
        let mut enums = enums::catalog(&client).await.unwrap();
        let original = enums
            .iter()
            .find(|t| t.schema == schema && t.name == "status")
            .unwrap()
            .clone();
        input = draft(&client, &schema, "enum_items").await;
        input.enum_changes.push(enums::EnumDraft {
            schema: schema.clone(),
            name: "status".into(),
            original: Some(original),
            values: vec!["new".into(), "ready".into(), "done".into()],
        });
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        assert_eq!(
            client
                .query_one(&format!("SELECT status::text FROM {enum_table}"), &[])
                .await
                .unwrap()
                .get::<_, String>(0),
            "new"
        );
        enums = enums::catalog(&client).await.unwrap();
        let original = enums
            .iter()
            .find(|t| t.schema == schema && t.name == "status")
            .unwrap()
            .clone();
        input = draft(&client, &schema, "enum_items").await;
        input.enum_changes.push(enums::EnumDraft {
            schema: schema.clone(),
            name: "status".into(),
            original: Some(original.clone()),
            values: vec!["new".into(), "ready".into(), "done".into(), "later".into()],
        });
        // PostgreSQL forbids using an added enum label until commit. Reject atomically.
        input.columns[0].default_mode = DefaultMode::Literal;
        input.columns[0].default_value = Some("later".into());
        assert!(apply(&client, &input, "", &committing, None).await.is_err());
        assert_eq!(
            enums::catalog(&client)
                .await
                .unwrap()
                .iter()
                .find(|t| t.schema == schema && t.name == "status")
                .unwrap()
                .values,
            original.values
        );
        input.columns[0].default_mode = DefaultMode::Keep;
        input.columns[0].default_value = input.expected.as_ref().unwrap()["columns"][0]
            ["defaultValue"]
            .as_str()
            .map(str::to_owned);
        client
            .batch_execute(&format!("ALTER TYPE {enum_name} ADD VALUE 'external'"))
            .await
            .unwrap();
        assert!(apply(&client, &input, "", &committing, None).await.is_err());
        // Existing enum selection, independently from creating its type.
        input = serde_json::from_value(serde_json::json!({
            "schema": schema, "table": "enum_copy", "original": null,
            "expected": null, "dropTable": false,
            "columns": [{"original":null,"name":"status","dataType":enum_name,
                "enumType":{"schema":schema,"name":"status"},"nullable":true,
                "primaryKey":false,"identity":false,"removed":false,"defaultValue":null}]
        }))
        .unwrap();
        assert!(apply(&client, &input, "", &committing, None).await.is_ok());
        client
            .batch_execute(&format!(
                "DROP TABLE {}, {enum_table}; DROP TYPE {enum_name}",
                qualified_table(&schema, "enum_copy")
            ))
            .await
            .unwrap();
        client
            .batch_execute(&format!(
                "DROP SCHEMA {} RESTRICT",
                quote_identifier(&schema)
            ))
            .await
            .unwrap();
    }
}
