use std::time::{SystemTime, UNIX_EPOCH};

use super::inspect;
use crate::database::{
    models::{ConnectionConfig, SslMode},
    postgres,
    table_data::quote_identifier,
};

#[tokio::test]
async fn inspects_structure_and_replays_ddl_when_postgres_is_configured() {
    let Ok(port) = std::env::var("OPALINE_TEST_POSTGRES_PORT") else {
        return;
    };
    let (client, _) = postgres::connect(&ConnectionConfig {
        name: "Structure test".into(),
        host: "127.0.0.1".into(),
        port: port.parse().expect("test port must be a number"),
        database: "postgres".into(),
        username: "postgres".into(),
        password: "opaline_test".into(),
        ssl_mode: SslMode::Disable,
        ca_path: None,
        read_only: false,
    })
    .await
    .expect("test database should connect");
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let schema = format!("opaline-structure-{}-{nonce}", std::process::id());
    let copy_schema = format!("{schema}-copy");
    let source = quote_identifier(&schema);
    let destination = quote_identifier(&copy_schema);
    client.batch_execute(&format!(
        "BEGIN; CREATE SCHEMA {source}; CREATE SCHEMA {destination}; \
         CREATE TABLE {source}.accounts (region text, id integer, PRIMARY KEY(region, id)); \
         CREATE TABLE {destination}.accounts (LIKE {source}.accounts INCLUDING ALL); \
         CREATE TABLE {source}.\"Order items\" ( \
           id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 42 INCREMENT BY 3 CACHE 7) PRIMARY KEY, \
           region text NOT NULL, account_id integer NOT NULL, name text NOT NULL DEFAULT 'untitled', \
           rank integer NOT NULL DEFAULT 1, doubled integer GENERATED ALWAYS AS (rank * 2) STORED, \
           CONSTRAINT order_account FOREIGN KEY (region, account_id) REFERENCES {source}.accounts(region, id) \
             ON UPDATE CASCADE ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED, \
           CONSTRAINT unique_name UNIQUE (name) \
         ) WITH (fillfactor=85); \
         ALTER TABLE {source}.\"Order items\" ADD CONSTRAINT positive_rank CHECK (rank > 0) NOT VALID; \
         CREATE INDEX order_search ON {source}.\"Order items\" (lower(name)) INCLUDE (rank) WHERE rank > 0; \
         COMMENT ON TABLE {source}.\"Order items\" IS E'Customer''s orders\\nsecond line'; \
         COMMENT ON COLUMN {source}.\"Order items\".name IS E'Customer-facing \\\\ label'; \
         CREATE VIEW {source}.order_names WITH (security_barrier=true) AS SELECT name FROM {source}.\"Order items\"; \
         CREATE MATERIALIZED VIEW {source}.order_summary AS SELECT count(*) AS total FROM {source}.\"Order items\" WITH NO DATA; \
         CREATE TABLE {source}.events (id integer, PRIMARY KEY(id)) PARTITION BY RANGE(id); \
         CREATE TABLE {source}.events_first PARTITION OF {source}.events FOR VALUES FROM (0) TO (10);"
    )).await.expect("structure fixtures should be created");

    let result = inspect(&client, &schema, "Order items")
        .await
        .expect("table should inspect");
    assert_eq!(result.columns.len(), 6);
    assert_eq!(result.columns[0].identity_generation, "d");
    assert!(result.columns[0]
        .identity_options
        .as_ref()
        .unwrap()
        .contains("START WITH 42"));
    assert_eq!(result.columns[5].generation_kind, "s");
    assert_eq!(
        result.comment.as_deref(),
        Some("Customer's orders\nsecond line")
    );
    let index = result
        .indexes
        .iter()
        .find(|index| index.name == "order_search")
        .unwrap();
    assert_eq!(index.columns, ["lower(name)"]);
    assert_eq!(index.included_columns, ["rank"]);
    assert!(index.predicate.is_some());
    let foreign_key = &result.foreign_keys[0];
    assert_eq!(foreign_key.source_columns, ["region", "account_id"]);
    assert_eq!(foreign_key.target_columns, ["region", "id"]);
    assert_eq!(foreign_key.on_delete, "RESTRICT");
    assert_eq!(foreign_key.on_update, "CASCADE");
    assert!(result
        .constraints
        .iter()
        .any(|constraint| constraint.name == "positive_rank" && !constraint.validated));
    let ddl = result.ddl.as_ref().expect("regular tables have DDL");
    assert_eq!(
        ddl.matches("CREATE UNIQUE INDEX").count(),
        0,
        "constraint indexes must not be duplicated"
    );
    client
        .batch_execute(&ddl.replace(&source, &destination))
        .await
        .expect("table DDL should execute");
    let replay = inspect(&client, &copy_schema, "Order items")
        .await
        .expect("recreated table should inspect");
    assert_eq!(replay.columns.len(), result.columns.len());
    assert_eq!(replay.indexes.len(), result.indexes.len());
    assert_eq!(replay.constraints.len(), result.constraints.len());
    assert_eq!(replay.comment, result.comment);
    assert_eq!(replay.columns[3].comment, result.columns[3].comment);
    assert_eq!(
        replay.columns[0].identity_options,
        result.columns[0].identity_options
    );

    let parent = inspect(&client, &schema, "accounts").await.unwrap();
    assert_eq!(parent.foreign_keys[0].direction, "incoming");
    for name in ["order_names", "order_summary", "events"] {
        let object = inspect(&client, &schema, name)
            .await
            .expect("view or partitioned table should inspect");
        client
            .batch_execute(&object.ddl.unwrap().replace(&source, &destination))
            .await
            .expect("view or partitioned table DDL should execute");
    }
    let partition = inspect(&client, &schema, "events_first").await.unwrap();
    assert!(
        partition.ddl.is_none(),
        "partition previews must not silently flatten inheritance"
    );
    assert_eq!(partition.object_type, "Partition");
    assert!(inspect(&client, &schema, "missing").await.is_err());
    assert!(
        inspect(&client, &schema, "Order items\"; DROP SCHEMA public; --")
            .await
            .is_err()
    );
    client
        .batch_execute("ROLLBACK")
        .await
        .expect("test schemas should roll back");
}
