import { useEffect, useRef, type KeyboardEvent } from "react";
import type { ColumnInfo } from "../../shared/types/database";
import type { InsertCellValue } from "./table-types";

type EditableCellProps = {
  column: ColumnInfo;
  value: string | null;
  autoFocus?: boolean;
  onChange: (value: string | null) => void;
  onCommit: () => void;
  onCancel: () => void;
  onUseDefault?: () => void;
};

export function EditableCell({
  column,
  value,
  autoFocus,
  onChange,
  onCommit,
  onCancel,
  onUseDefault,
}: EditableCellProps) {
  if (column.identity || column.generated) return <CellValue value={value} />;

  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Escape") onCancel();
    if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
      event.preventDefault();
      onCommit();
    }
  };

  return (
    <div className={`cell-editor ${value === null ? "is-null" : ""}`}>
      <input
        autoFocus={autoFocus}
        value={value ?? ""}
        disabled={value === null}
        aria-label={`Value for ${column.name}`}
        onChange={(event) => onChange(event.target.value)}
        onKeyDown={handleKeyDown}
      />
      <div className="cell-editor-options">
        {column.nullable && (
          <button
            type="button"
            aria-label={
              value === null ? `Set a value for ${column.name}` : `Set ${column.name} to NULL`
            }
            aria-pressed={value === null}
            onClick={() => onChange(value === null ? "" : null)}
          >
            NULL
          </button>
        )}
        {onUseDefault && (
          <button
            type="button"
            aria-label={`Use the PostgreSQL default for ${column.name}`}
            onClick={onUseDefault}
          >
            DEFAULT
          </button>
        )}
      </div>
    </div>
  );
}

type InsertCellProps = {
  column: ColumnInfo;
  value: InsertCellValue;
  autoFocus: boolean;
  onChange: (value: InsertCellValue) => void;
  onCommit: () => void;
  onCancel: () => void;
};

export function InsertCell({
  column,
  value,
  autoFocus,
  onChange,
  onCommit,
  onCancel,
}: InsertCellProps) {
  if (column.identity || column.generated) {
    return (
      <span
        className="insert-cell-managed"
        title={column.generated ? "Computed by PostgreSQL" : "Generated by PostgreSQL"}
      >
        {column.generated ? "GENERATED" : "AUTO"}
      </span>
    );
  }
  if (value === undefined) {
    return (
      <button
        type="button"
        className="insert-cell-default"
        title={column.defaultValue ?? "Use the PostgreSQL default"}
        onClick={() => onChange("")}
      >
        <span>DEFAULT</span>
        <small>Click to override</small>
      </button>
    );
  }
  return (
    <EditableCell
      column={column}
      value={value}
      autoFocus={autoFocus}
      onChange={onChange}
      onCommit={onCommit}
      onCancel={onCancel}
      onUseDefault={column.defaultValue !== null ? () => onChange(undefined) : undefined}
    />
  );
}

export function CellValue({ value }: { value: string | null }) {
  return value === null ? (
    <span className="table-null">NULL</span>
  ) : (
    <span className="table-cell-value" title={value}>
      {value}
    </span>
  );
}

type SelectionCheckboxProps = {
  checked: boolean;
  indeterminate?: boolean;
  label: string;
  disabled?: boolean;
  onChange: () => void;
};

export function SelectionCheckbox({
  checked,
  indeterminate = false,
  label,
  disabled,
  onChange,
}: SelectionCheckboxProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (inputRef.current) inputRef.current.indeterminate = indeterminate;
  }, [indeterminate]);

  return (
    <input
      ref={inputRef}
      className="table-selection-checkbox"
      type="checkbox"
      checked={checked}
      disabled={disabled}
      aria-label={label}
      onChange={onChange}
    />
  );
}
